# STS3 Grouping data

## Step 1. Import the libraries, load the survey and check if it works.

## You must run this code!!!

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

survey = pd.read_csv('survey.csv')

In [3]:
survey

,Index,Q1,Q1_text,Q2,Q2_text,Q3,Q3_text,Q4,Q4_text,Q5,...,Q24,Q24_text,Q25,Q25_text,Q26,Q26_text,Q27,Q27_text,Q28,Q28_text
0,6101,1,Grade 6,1,Male,2,With parents,2,No,2,...,2.0,Once a year,5.0,Very healthy,3.0,Neutral,4.0,Useful,4.0,A few times a week
1,6102,1,Grade 6,1,Male,2,With parents,2,No,3,...,5.0,Every day,5.0,Very healthy,4.0,Quite motivated,3.0,Neutral,3.0,Once a week
2,6103,1,Grade 6,2,Female,2,With parents,1,Yes,1,...,1.0,Never,3.0,Neutral,1.0,Not motivated at all,5.0,Very useful,4.0,A few times a week
3,6104,1,Grade 6,2,Female,1,Dorm,1,Yes,3,...,3.0,Once a month,4.0,Healthy,2.0,A little,2.0,A little,4.0,A few times a week
4,6105,1,Grade 6,1,Male,2,With parents,2,No,3,...,4.0,Once a week,3.0,Neutral,3.0,Neutral,5.0,Very useful,3.0,Once a week
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,8017,3,Grade 8,1,Male,2,With parents,2,No,4,...,3.0,Once a month,5.0,Very healthy,4.0,Quite motivated,4.0,Useful,4.0,A few times a week
183,8018,3,Grade 8,2,Female,1,Dorm,2,No,4,...,1.0,Never,3.0,Neutral,1.0,Not motivated at all,2.0,A little,2.0,Once a month
184,8019,3,Grade 8,1,Male,2,With parents,2,No,5,...,2.0,Once a year,5.0,Very healthy,5.0,Very motivated,5.0,Very useful,5.0,Every day
185,8020,3,Grade 8,1,Male,2,With parents,2,No,4,...,4.0,Once a week,4.0,Healthy,5.0,Very motivated,5.0,Very useful,5.0,Every day
186,8021,3,Grade 8,1,Male,2,With parents,2,No,4,...,4.0,Once a week,5.0,Very healthy,5.0,Very motivated,5.0,Very useful,5.0,Every day

## Okay, now everything else should work :)

We know how to calculate percentages for any question! 

We can change the code to work for any question we want. 

`my_question_percentages = (survey['my_question'].value_counts(normalize=True) * 100).round(0)`

In [4]:
# Create a variable to calculate percentages 

#Q3 "What's your living situation?"
Q3_percentages = (survey['Q3_text'].value_counts(normalize=True) * 100).round(0)


Q3_percentages

Q3_text
With parents         74.0
Dorm                 11.0
Other                11.0
With grandparents     3.0
Name: proportion, dtype: float64

### Sometimes we want to see answers divided by different groups. 

We might want to see if there is a difference between how students answered in **different grades**.

Or  we might want to see if there is a difference between boys and girls.

To see that we need to add `groupby`

In [6]:
# Calculate percentages for Q3 grouped by Q1_text (grade)
# What's the living situation in different grades? %

Q3_by_grade = (survey.groupby('Q1_text')['Q3_text'].value_counts(normalize=True).unstack() * 100).round(0)

Q3_by_grade

Q3_text  Dorm  Other  With grandparents  With parents
Q1_text
Grade 6   6.0   15.0                4.0          75.0
Grade 7  15.0    9.0                NaN          77.0
Grade 8  14.0    9.0                4.0          72.0

In `groupby` we first add the question by which we are grouping. 

For example we write `('Q1_text')` first to group by Grade. 

Then we write the question we want to check, such as the living situation: `['Q3_text']`.

 First we use `()`, then we use `[]`.

## THINK!


### What questions can we group by?

-----


Okay! Let's check which grade is the most confident in speaking English.

To do that we need to take a look at `'Q13_text'` and group it by `'Q1_text.'`

In [10]:
Q7_by_grade = (survey.groupby('Q1_text')['Q13_text'].value_counts(normalize=True).unstack() * 100).round(0)

Q7_by_grade

Q13_text,A little,Neutral,Not confident at all,Quite confident,Very confident
Q1_text,,,,,
Grade 6,28.0,20.0,16.0,23.0,13.0
Grade 7,21.0,35.0,19.0,12.0,12.0
Grade 8,26.0,33.0,17.0,14.0,10.0

What about girls and boys? 

Let's see who feels more confident!

To do that we need to take a look at `'Q7_text'` and group it by `'Q2_text.'`

In [12]:
Q7_by_gender = (survey.groupby('Q2_text')['Q13_text'].value_counts(normalize=True).unstack() * 100).round(0)

Q7_by_gender

Q13_text,A little,Neutral,Not confident at all,Quite confident,Very confident
Q2_text,,,,,
Female,29.0,32.0,15.0,13.0,11.0
Male,22.0,26.0,19.0,21.0,13.0

### Exercise: Choose a question a group it by grade. `groupby('Q1_text')`

In [ ]:
Qxx_by_grade = (survey.groupby('Q1_text')['Qxx_text'].value_counts(normalize=True).unstack() * 100).round(0)

Qxx_by_grade

### Exercise: Choose a question a group it by gender. `groupby('Q2_text')`

In [ ]:
Qxx_by_gender = (survey.groupby('Q2_text')['Qxx_text'].value_counts(normalize=True).unstack() * 100).round(0)

Qxx_by_gender